Node js
AlexAllGold/sports-keeper pull request #7
Opened 2023-03-21 21:37 UTC by AlexAllGold

feat/dtos/#4

2023-03-21 21:43 UTC, AlexAllGold commented
Added feat: bodyParser.js, validator.dot.js, client.dot.js

2023-03-22 19:49 UTC, Sk3ll requested changes

2023-03-22 19:49 UTC, Sk3ll commented on src/router/index.js
> +    const message = 'Not found!!!';
?

2023-03-22 19:49 UTC, Sk3ll commented on .prettierrc.json
> +  "jsxBracketSameLine": false
Тебе не нужен jsx, у тебя node.js

2023-03-22 19:49 UTC, Sk3ll commented on src/controllers/clubsControllers.js
> +      throw new Error(`Error in getAll(): ${err.message}`);
у тебя должен быть глобальный errorHandler, а не каждый раз ты будешь ловить тут, удали try catch

2023-03-22 19:49 UTC, Sk3ll commented on src/dtos/сlient.dto.js
> +    if (this.lastName.length >= 4 && this.lastName <= 50) {
Вынеси эти проверки в min() и max() методы в Validator

2023-03-22 19:49 UTC, Sk3ll commented on src/dtos/сlient.dto.js
> +    if (this.email.length >= 3 && this.email <= 256) {
Здесь должен быть regex для email

2023-03-22 19:49 UTC, Sk3ll commented on src/dtos/сlient.dto.js
> +    throw new Error('Invalid first name or last name');
Все ошибки в валидаторе должны быть, а не в Dto

2023-03-22 19:49 UTC, Sk3ll commented on src/utils/bodyParser.js
> +      try {
убери try catch

2023-03-22 19:49 UTC, Sk3ll commented on src/utils/bodyParser.js
> +          .on('data', (chunk) => {
```suggestion
          .on('error', (error) => {
            reject(error);
```

2023-03-22 19:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    if (!Number.isNaN(Number(number))) {
это проверка на NaN, а не число

2023-03-22 19:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +      return String(firstName);
`String('12') // '12' `

это не правильная проверка

2023-03-22 19:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    const date = new Date(dateOfBirth.split('-'));
Это не правильна проверка на дату

2023-03-28 17:49 UTC, Sk3ll requested changes

2023-03-28 17:49 UTC, Sk3ll commented on src/controllers/clubsControllers.js
> +  async getOne(res, params) {
Why should you use `async` here?

2023-03-28 17:49 UTC, Sk3ll commented on src/dtos/сlient.dto.js
> +    this.firstName = this.isName(client.firstName);
Что означает `isName`? Тебе надо проверять на стрингу, то есть это isString

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/bodyParser.js
> +        .on('error', (error) => {
а где `.on('data')`?

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    if (dateOfBirth instanceof Date) {
Тут должен быть regex для даты, при том дата рождения должна быть не больше текущей даты и не старше чем 100 лет

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    if (this.#isMin(name) && this.#isMax(name)) {
min, max должны проверяться отдельными методами. А здесь должна быть проверка на стрингу

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    if (number instanceof Number) {
Здесь должна быть проверка на намбер, то есть regex

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +    if (min.length >= 4) {
Это не правильно

2023-03-28 17:49 UTC, Sk3ll commented on src/utils/validator.dto.js
> +export class ValidatorDto {
Валидатор - это валидатор. Это не дто. Убери с названия файла .dto и из названия класса тоже

2023-04-27 19:02 UTC, Sk3ll commented on src/utils/sendResponse.js
>    res.setHeader('Content-Type', 'text/plain');
```suggestion
  res.setHeader('Content-Type', 'application/json');
```

2023-04-27 19:04 UTC, Sk3ll commented on src/services/clientService.js
> +          resolve(results);
А что если id не найден в твое базе?

2023-04-27 19:05 UTC, Sk3ll commented on src/services/clientService.js
> +          (err, results) => {
а что если такой записи нет в базе данных по такому id? надо добавит бизнес логику для этого

2023-04-27 19:05 UTC, Sk3ll commented on src/services/clientService.js
> +            reject(err);
А что если уже нету записи с таким id?

2023-04-28 08:23 UTC, Sk3ll commented on src/router/index.js
> +  const getController = (url) => routes.find((route) => route.path === findRouter(url, route.path));
```suggestion
  const getController = (url) => 
     routes.find((route) => route.path === findRouter(url, route.path))?
     .methods[req.method];
```

2023-04-28 08:23 UTC, Sk3ll commented on src/router/index.js
> +  const findRouter = (url, rout) => {
```suggestion
  const findMatchedPath = (url, rout) => {
```

2023-05-07 20:54 UTC, Sk3ll approved these changes

2023-05-07 21:11 UTC, merged